CREATE TABLE IF NOT EXISTS `M_KEY` (
  `key` VARCHAR (36) NOT NULL PRIMARY KEY,
  `total` TINYINT UNSIGNED NOT NULL DEFAULT '0',
  `expire` VARCHAR(15) NOT NULL DEFAULT '19700101T090000'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
