CREATE TABLE IF NOT EXISTS `M_KEY` (
  `key` VARCHAR (36) NOT NULL PRIMARY KEY,
  `total` TINYINT UNSIGNED NOT NULL DEFAULT '0',
  `expire` VARCHAR(19) NOT NULL DEFAULT '1970-01-01T09:00:00'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
